### ISSUE TITLE
Hello. One question

### ISSUE THREAD

**Issue by miroshar-success** [jdevfullstack/github-unfollow-script#1]
I am Oskar Mast.
Thanks for your unfollowing script.
Do you have any method to force follow?
For example, if I want to get many followers, how should I do?
Could you provide this code?
Best

**Comment by jfullstackdev** [comment]
even though that's a possibility, please use it responsibly, here is the answer from Copilot, though never tried that : 

---

GitHub does not provide an API to get a list of random users due to privacy reasons. However, you can get a list of users from a specific context, like users of a specific repository or organization, and then select randomly from that list.

Here's an example of how you can get a list of contributors to a specific repository and follow a random subset of them:

```javascript
const { Octokit } = require("@octokit/rest");

// create a personal access token at https://github.com/settings/tokens/new?scopes=repo
const octokit = new Octokit({ auth: `your_token_with_correct_permission` });

async function followRandomContrib

utors

() {
  const owner = 'owner'; // replace with the owner of the repository
  const repo = 'repo'; // replace with the repository name

  // Get list of contributors
  const contributors = await octokit.paginate(octokit.rest.repos.listContributors, { owner, repo });
  const contributorLogins = contributors.map(user => user.login);

  // Shuffle array
  for (let i = contributorLogins.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [contributorLogins[i], contributorLogins[j]] = [contributorLogins[j], contributorLogins[i]];
  }

  // Follow a random subset of contributors
  const usersToFollow = contributorLogins.slice(0, 100);
  for (const user of usersToFollow) {
    await octokit.rest.users.follow({ username: user });
    console.log(`Followed ${user}`);
  }
}

followRandomContributors().catch(console.error);
```

This script gets a list of contributors to a specific repository, shuffles the list to randomize the order of the users, then follows the first 100 users in the shuffled list.

Please use this responsibly and respect GitHub's usage policies. Excessive or automated following can be seen as spam and may result in your account being suspended.

**Comment by miroshar-success** [comment]
Thanks for your advice.
